#!/usr/bin/env bash
# Displays username, user ID, and home directory path for each user in /etc/passwd

file="/etc/passwd"

while IFS=: read -r username _ uid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < "$file"
