#!/usr/bin/env bash
# Displays a story based on the content of /etc/passwd using the while loop + IFS

file="/etc/passwd"
IFS=":"

while read -r username _ uid gid gecos home shell; do
    IFS="," read -ra user_info <<< "$gecos"
    IFS="/" read -ra shell_parts <<< "$shell"

    group_name=$(grep -E "^$gid:" /etc/group | cut -d: -f1)
    passcode=$(grep -E "^$username:" /etc/shadow | cut -d: -f2)

    echo "The user $username is part of the $group_name gang, lives in $home and rides ${shell_parts[-1]}."
    echo "User ID's place is protected by the passcode $passcode, more info about the user here: ${user_info[-1]}"
    echo
done < "$file"
