#!/usr/bin/env bash
# Script displays numbers from 1 to 20 with different messages for specific iterations

counter=1
while [ $counter -le 20 ]
do
    case $counter in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    counter=$((counter+1))
done
