#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

HOUR=0
while (( HOUR<=12 )); do
    echo "Hour: $HOUR"
    MINUTE=1
    while [ "$MINUTE" -lt 60 ]; do
        echo "$MINUTE"
        ((MINUTE++))
        if [ "$MINUTE" -eq 60 ]; then
            break
        fi
    done
    ((HOUR++))
done
