#!/usr/bin/env bash

# Bash script to display the time from 0:01 to 12:59

hours=0
minutes=1

while [ $hours -lt 13 ]; do
    while [ $minutes -lt 60 ]; do
        echo "$hours:$minutes"
        minutes=$((minutes + 1))
    done
    hours=$((hours + 1))
    minutes=0
done

